"""empty message

Revision ID: 0bfd04ddf3d8
Revises: 76c85ff98622
Create Date: 2022-07-08 17:31:40.190291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bfd04ddf3d8'
down_revision = '76c85ff98622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('current_points', sa.Integer(), nullable=True),
    sa.Column('total_goals', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('team_name'),
    mysql_engine='InnoDB'
    )
    op.create_table('matches',
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('opponent', sa.String(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('current_points', sa.Integer(), nullable=True),
    sa.Column('total_goals', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opponent'], ['teams.team_name'], ),
    sa.ForeignKeyConstraint(['team'], ['teams.team_name'], ),
    sa.PrimaryKeyConstraint('team', 'opponent', 'round'),
    mysql_auto_increment='1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('teams')
    # ### end Alembic commands ###
