"""empty message

Revision ID: 2a3f52c7e172
Revises: c1eeebd9606a
Create Date: 2022-07-08 23:49:09.394889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3f52c7e172'
down_revision = 'c1eeebd9606a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('wins', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('draws', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('losses', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'losses')
    op.drop_column('teams', 'draws')
    op.drop_column('teams', 'wins')
    # ### end Alembic commands ###
