"""empty message

Revision ID: 2f8de6f7a8b6
Revises: 2a3f52c7e172
Create Date: 2022-07-10 02:55:36.199085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8de6f7a8b6'
down_revision = '2a3f52c7e172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('team_name', sa.String(length=50), nullable=False),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('current_points', sa.Integer(), nullable=True),
    sa.Column('total_goals', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('team_name'),
    mysql_engine='InnoDB'
    )
    op.create_table('matches',
    sa.Column('team', sa.String(length=50), nullable=False),
    sa.Column('opponent', sa.String(length=50), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('team_goals', sa.Integer(), nullable=True),
    sa.Column('opponent_goals', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opponent'], ['teams.team_name'], ),
    sa.ForeignKeyConstraint(['team'], ['teams.team_name'], ),
    sa.PrimaryKeyConstraint('team', 'opponent', 'round'),
    mysql_auto_increment='1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('teams')
    # ### end Alembic commands ###
