"""empty message

Revision ID: 76c85ff98622
Revises: 
Create Date: 2021-10-30 00:17:58.078029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c85ff98622'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('course_name'),
    mysql_engine='InnoDB'
    )
    op.create_table('employees',
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('designation', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    mysql_engine='InnoDB'
    )
    op.create_table('administrators',
    sa.Column('admin_username', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['admin_username'], ['employees.username'], ),
    sa.PrimaryKeyConstraint('admin_username'),
    mysql_engine='InnoDB'
    )
    op.create_table('engineers',
    sa.Column('engineer_username', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['engineer_username'], ['employees.username'], ),
    sa.PrimaryKeyConstraint('engineer_username'),
    mysql_engine='InnoDB'
    )
    op.create_table('prerequisite_courses',
    sa.Column('course_name', sa.String(length=50), nullable=False),
    sa.Column('prerequisite_course_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['course_name'], ['courses.course_name'], ),
    sa.PrimaryKeyConstraint('course_name', 'prerequisite_course_name'),
    mysql_engine='InnoDB'
    )
    op.create_table('classes',
    sa.Column('course_name', sa.String(length=50), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=False),
    sa.Column('trainer_username', sa.String(length=50), nullable=True),
    sa.Column('enrollment_start_date', sa.DateTime(), nullable=True),
    sa.Column('enrollment_end_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_name'], ['courses.course_name'], ),
    sa.ForeignKeyConstraint(['trainer_username'], ['engineers.engineer_username'], ),
    sa.PrimaryKeyConstraint('course_name', 'class_name'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_classes_class_name'), 'classes', ['class_name'], unique=False)
    op.create_index(op.f('ix_classes_course_name'), 'classes', ['course_name'], unique=False)
    op.create_table('learners',
    sa.Column('engineer_username', sa.String(length=50), nullable=False),
    sa.Column('contact_no', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['engineer_username'], ['engineers.engineer_username'], ),
    sa.PrimaryKeyConstraint('engineer_username'),
    mysql_engine='InnoDB'
    )
    op.create_table('trainers',
    sa.Column('engineer_username', sa.String(length=50), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['engineer_username'], ['engineers.engineer_username'], ),
    sa.PrimaryKeyConstraint('engineer_username'),
    mysql_engine='InnoDB'
    )
    op.create_table('enrolled_classes',
    sa.Column('course_name', sa.String(length=50), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=False),
    sa.Column('engineer_username', sa.String(length=50), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['class_name'], ['classes.class_name'], ),
    sa.ForeignKeyConstraint(['course_name'], ['classes.course_name'], ),
    sa.ForeignKeyConstraint(['engineer_username'], ['engineers.engineer_username'], ),
    sa.PrimaryKeyConstraint('course_name', 'class_name', 'engineer_username'),
    mysql_engine='InnoDB'
    )
    op.create_table('lessons',
    sa.Column('lesson_no', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=False),
    sa.Column('lesson_title', sa.String(length=50), nullable=True),
    sa.Column('course_name', sa.String(length=50), nullable=False),
    sa.Column('is_last_lesson', sa.Boolean(), nullable=True),
    sa.Column('lesson_materials_url', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['class_name', 'course_name'], ['classes.class_name', 'classes.course_name'], ),
    sa.PrimaryKeyConstraint('lesson_no', 'class_name', 'course_name'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_lessons_class_name'), 'lessons', ['class_name'], unique=False)
    op.create_index(op.f('ix_lessons_course_name'), 'lessons', ['course_name'], unique=False)
    op.create_table('completed_lessons',
    sa.Column('engineer_username', sa.String(length=50), nullable=False),
    sa.Column('course_name', sa.String(length=50), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=False),
    sa.Column('lesson_no', sa.Integer(), nullable=False),
    sa.Column('is_last_lesson', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['class_name'], ['lessons.class_name'], ),
    sa.ForeignKeyConstraint(['course_name'], ['lessons.course_name'], ),
    sa.ForeignKeyConstraint(['engineer_username'], ['engineers.engineer_username'], ),
    sa.ForeignKeyConstraint(['lesson_no'], ['lessons.lesson_no'], ),
    sa.PrimaryKeyConstraint('engineer_username', 'course_name', 'class_name', 'lesson_no'),
    mysql_engine='InnoDB'
    )
    op.create_table('quizzes',
    sa.Column('quiz_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_no', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=False),
    sa.Column('course_name', sa.String(length=50), nullable=False),
    sa.Column('passing_percentage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_no', 'class_name', 'course_name'], ['lessons.lesson_no', 'lessons.class_name', 'lessons.course_name'], ),
    sa.PrimaryKeyConstraint('quiz_id', 'lesson_no', 'class_name', 'course_name'),
    mysql_auto_increment='1',
    mysql_engine='InnoDB'
    )
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('question_description', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.quiz_id'], ),
    sa.PrimaryKeyConstraint('question_id', 'quiz_id'),
    mysql_auto_increment='1',
    mysql_engine='InnoDB'
    )
    op.create_table('answers',
    sa.Column('answer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('answer_description', sa.String(length=300), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('answer_id', 'question_id'),
    mysql_auto_increment='1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('questions')
    op.drop_table('quizzes')
    op.drop_table('completed_lessons')
    op.drop_index(op.f('ix_lessons_course_name'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_class_name'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_table('enrolled_classes')
    op.drop_table('trainers')
    op.drop_table('learners')
    op.drop_index(op.f('ix_classes_course_name'), table_name='classes')
    op.drop_index(op.f('ix_classes_class_name'), table_name='classes')
    op.drop_table('classes')
    op.drop_table('prerequisite_courses')
    op.drop_table('engineers')
    op.drop_table('administrators')
    op.drop_table('employees')
    op.drop_table('courses')
    # ### end Alembic commands ###
