"""empty message

Revision ID: 9c140226ed30
Revises: 148ead86e545
Create Date: 2022-07-11 13:16:27.934236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c140226ed30'
down_revision = '148ead86e545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_members', sa.Column('spouse', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('family_members', 'spouse')
    # ### end Alembic commands ###
