"""empty message

Revision ID: c1eeebd9606a
Revises: 0793560dc92b
Create Date: 2022-07-08 17:46:14.974344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1eeebd9606a'
down_revision = '0793560dc92b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('team_goals', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('opponent_goals', sa.Integer(), nullable=True))
    op.drop_column('matches', 'current_points')
    op.drop_column('matches', 'total_goals')
    op.drop_column('matches', 'registration_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('registration_date', mysql.DATETIME(), nullable=True))
    op.add_column('matches', sa.Column('total_goals', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('current_points', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('matches', 'opponent_goals')
    op.drop_column('matches', 'team_goals')
    # ### end Alembic commands ###
